version: "2"

run:
  timeout: 10m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: standard
  enable:
    - bodyclose
    - contextcheck
    - err113
    - errname
    - errorlint
    - exhaustive
    - gocritic
    - gosec
    - loggercheck
    - misspell
    - modernize
    - nilerr
    - nilnil
    - nilnesserr
    - nolintlint
    - perfsprint
    - predeclared
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usetesting
    - usestdlibvars
    - wastedassign
    - wrapcheck
    - canonicalheader
    - copyloopvar
    - durationcheck
    - fatcontext
